### ISSUE TITLE
Use a different ordering of keybindings

### ISSUE THREAD

**Issue by Crystal4276** [sbk2017/qtile-scripts#2]
Hi !
Nice script.
I was wondering if you would consider a different ordering of the keybindings?
Ideally, i'd like to have keybindings in this  order:
- no mod4
- Only mod 4
- mod 4 + ctrl
- mod 4 + shift
- mod4 + mod1

It will improve the logic for the grouping of keybindings.
Cf screenshot below.
![image](https://user-images.githubusercontent.com/27446196/201523102-ffaed065-5028-458c-85b6-9de1868bf5db.png)

**Comment by sbk2017** [comment]
Hi
Thanks .. 
The order you have suggest was the initial order .. but it was difficult to find which key does what.
I am happy to add your suggestion as an option and also I am planing add simple search from the description.

**Comment by Crystal4276** [comment]
Oh cool !
Another way is to sort them in the same order as they appear in config.py.
This is because it's ordered in qtile config.py in a sensible way (at least to me)
So i guess just reading through it would be fine too.

**Comment by sbk2017** [comment]
The script now include sorting and searching options.

**Comment by Crystal4276** [comment]
I tested all new options 
Great job, thanks a lot !

**Comment by sbk2017** [comment]
👍 ..
